### ISSUE TITLE
Is there a way to get scalars (N, N_treated, N_control, etc.) from RIF files?

### ISSUE THREAD

**Issue by Mbjoerkh** [friosavila/stpackages#1]
Hi, 

Thanks for making a great set of tools.. 

I have a simple question. Is there a way to get the usual scalars (N, N_treated, N_control, etc.) from a "_RIF_" file?

Use case: Since the estimations I'm doing are time consuming, I've run a loop over several outcomes overnight using the saverif option. It would be good if there was a way to get the usual scalars from the csdid_stats or csdid_rif commands.
Thanks!

```
foreach y in y1 y2 ... yN {
	csdid `y' , ivar(id) time(period) gvar(event_period) saverif(_`y') replace  
}
```

**Comment by friosavila** [comment]
Hi Markus
mmm, unfortunately not. I havent figure out how to save those in the RIF
file.
However, something you could do is to save the e() data
perhaps:

foreach y in y1 y2 ... yN {
	csdid `y' , ivar(id) time(period) gvar(event_period) saverif(_`y') replace

        est save _`y', replace
}

this will create a STER file where the N, N_treated, N_control will be
available.

F
