### ISSUE TITLE
Potentially Problematic Pretrends

### ISSUE THREAD

**Issue by JamesMaxwellHarrison** [friosavila/stpackages#3]
For ATT's before the treatment took place, the default uses T-1 as the base period (or Pre-period), and T as the post-period. This can potentially obscure problematic pretrends. For example, a moderate positive pre-trend would be masked as coefficients that are consistently slightly above zero but perhaps not statistically significant. I believe that only very careful readers with intimate knowledge of this package would catch such nuances. I recommend making option long or long2 the default to avoid this issue.

![image](https://github.com/friosavila/stpackages/assets/65124297/52b66391-bc4d-465a-bdea-81ceedbb21bd)

![image](https://github.com/friosavila/stpackages/assets/65124297/ed3ddd95-702d-4fa4-8976-827953daa9cf)

Edit: I edited the default graph so that period -1 matches Callaway Sant'Anna

**Comment by friosavila** [comment]
I agreed
I modified that in csdid2. 
The only reason I haven't changed it in csdid is because last time I checked did in R also uses it as default (following the original paper)
Same reason why xthdidregress uses same default.
That being said, package is overdue for an update
F

**Comment by JamesMaxwellHarrison** [comment]
Thanks for the reply. I did not know of those differences between csdid and csdid2. For what it's worth, it appears that xthdidregress has the same default as csdid and gives misleading pre-trends.

```
use https://www.stata-press.com/data/r18/akc, clear
xtset breed year
xthdidregress ra (registered best) (movie), group(breed) cohortvar(cohort, replace)
estat aggregation, dynamic graph
csdid registered best, ivar(breed) time(year) gvar(cohort) method(reg) agg(event)
* Both have the same pre-trends.
```

I had been avoiding xthdidregress because their AIPW results seem off. AIPW always matches their RA results and do not match csdid results. I reported the issue to Stata this morning.

**Comment by friosavila** [comment]
Ohh, that is good to know about xthdidregress. For obvious reasons i have
not use it beyond speed tests
But, because Stata is mostly based on paper/backed estimators, they are a
bit tied regarding using "long2" as the default option for pre-trends.
Not sure if they will offer the option at some point
