### ISSUE TITLE
csdid2 not running

### ISSUE THREAD

**Issue by cfbalcazar** [friosavila/stpackages#6]
Hi! I want to use the new mata version of csdid, however I'm getting the following error:

```
frause mpdta, clear
csdid2 lemp, ivar(countyreal) tvar(year) gvar(first)
Producing Long Gaps by default
Using method reg
                 <istmt>:  3499  csdid() not found
r(3499);
```

I'm wondering if this perhaps a bug related to the new csdid script. Using tracing, I find that the following error:

```
    ------------------------------------------------------------- end _xtreg_chk_cl2 ---
  - }
  - if "`cluster'"!="" {
  = if ""!="" {
    if "`ivar'"!="" _xtreg_chk_cl2 `cluster' `ivar' `touse'
    }
  - if "`ivar'"!="" {
  = if "countyreal"!="" {
  - mata:balance("`ivar'","`tvar'","`touse'")
  = mata:balance("countyreal","year","__000002")
  - }
  - local cvar `cluster'
  = local cvar 
  - mata:`csname'=csdid()
  = mata:csdid=csdid()
                 <istmt>:  3499  csdid() not found
  --------------------------------------------------------------- end csdid2.csdid_r ---
------------------------------------------------------------------------- end csdid2 ---
r(3499);
```

Stata version: 17 MP 2-core
OS: MacOS 12.5 
M1 structure

**Comment by friosavila** [comment]
Did you check on installing the full csdid2? (fra install)
there are some mata libraries that also need to be on your computer, without them, you can run the command

**Comment by friosavila** [comment]
perhaps best method
net install csdid2, from("
https://raw.githubusercontent.com/friosavila/stpackages/main") replace
That should work.
F
