### ISSUE TITLE
panels are not nested within clusters +unbalanced data

### ISSUE THREAD

**Issue by kikiwong333** [friosavila/stpackages#7]
csdid2 lnwwe, ivar(groupid) tvar(year) gvar(gvar)     
Producing Long Gaps by default
Using method reg
panels are not nested within clusters

I want to ask :Can unbalanced panel data be used with csdid2? I tried, and it gave me such results:panels are not nested within clusters
Thanks a lot

**Comment by friosavila** [comment]
Yes
Like with csdid you need to drop ivar() and probably use “cluster()” instead
This forces the command to use data as repeated crossection
