### ISSUE TITLE
Plot not working

### ISSUE THREAD

**Issue by bbomikang** [friosavila/stpackages#8]
Hi, 

Thanks for the package! It is indeed way faster than csdid. I have one quick question.

I am having trouble to plot the result. When I run `estat event, wboot plot` I got the following error message:

WildBootstrap Standard errors
with 999 Repetitions
program myencode not found
(error occurred while loading csdid2_plot.ado)

Could you please help me to solve this problem?
Thank you!

**Comment by bbomikang** [comment]
Thank you, it worked! would you please let me know if Ithere is any way that I can restrict the windows?

**Comment by friosavila** [comment]
perhaps something like
estat event, revent(-5/5)
where the syntax is to add a list of numbers in revent(numlist) to restrict
which events one wants to estimate the effects for
